### ISSUE TITLE
Rewrite for Laravel 5.x with new methods

### ISSUE THREAD

**Issue by Braunson** [Braunson/fatsecret-laravel#4]
Rewrite the whole package for Laravel 5.x with more helpful methods that better integrate into FatSecret.

I'm open to suggestions and help 😄

**Comment by namelivia** [comment]
I can take this one!

**Comment by Braunson** [comment]
@namelivia Go for it! I was thinking of adding a few more helper methods and refactoring what's already there down a bit.

**Comment by namelivia** [comment]
Ok! I'll include some of that in the PR aswell

**Comment by Braunson** [comment]
Thanks @namelivia for all of your help, I've added a new release!
