### ISSUE TITLE
The composer require example on the README seems wrong

### ISSUE THREAD

**Issue by namelivia** [Braunson/fatsecret-laravel#7]
The README file states that for including the package in a laravel project it is neccesary to execute:
`$ composer require "braunson/fatsecret"`

But I see [the package named on Packagist](https://packagist.org/packages/braunson/fatsecret-laravel) as `"braunson/fatsecret-laravel"` so for including it would be like:
`$ composer require "braunson/fatsecret-laravel"`

**Comment by Braunson** [comment]
Thanks, it was renamed a while back, I've updated the README!
